/** Core type file: defines shared TypeScript contracts used across routes, controllers, middleware, and services. */
export interface UploadedFile {
  // Original filename sent by the browser.
  originalname: string;
  // Stored filename generated by the server.
  filename: string;
  // Browser-provided MIME type, checked against route allow-lists where needed.
  mimetype: string;
  // File size in bytes after buffering or streaming.
  size: number;
  // Buffer is present only for small imports that need in-memory parsing.
  buffer?: Buffer;
}
